
INSERT INTO SHSTPRODUCT (CATEGORYID, BARCODE, NAME, DESCRIPTION, PRICE, STOCK, STATUS, CREATEDDATE, VERSION)
VALUES (1,'654321', 'Camiseta IronMan', '', 10, 50, '1', CURRENT_TIMESTAMP, 0);

INSERT INTO SHSTPRODUCT (CATEGORYID, BARCODE, NAME, DESCRIPTION, PRICE, STOCK, STATUS, CREATEDDATE, VERSION)
VALUES (2,'654322', 'Vaso IronMan Kids', '', 5, 5, '1', CURRENT_TIMESTAMP, 0);

INSERT INTO SHSTPRODUCT (CATEGORYID, BARCODE, NAME, DESCRIPTION, PRICE, STOCK, STATUS, CREATEDDATE, VERSION)
VALUES (3,'654323', 'The last adventure Spiderman - Comic', '', 7, 7, '1', CURRENT_TIMESTAMP, 0);

INSERT INTO SHSTPRODUCT (CATEGORYID, BARCODE, NAME, DESCRIPTION, PRICE, STOCK, STATUS, CREATEDDATE, VERSION)
VALUES (4,'654324', 'Mini Superman Lego', '', 20, 2, '1', CURRENT_TIMESTAMP, 0);

INSERT INTO SHSTPRODUCT (CATEGORYID, BARCODE, NAME, DESCRIPTION, PRICE, STOCK, STATUS, CREATEDDATE, VERSION)
VALUES (4,'664321', 'Juguete Batman', '', 10, 50, '1', CURRENT_TIMESTAMP, 0);

INSERT INTO SHSTPRODUCT (CATEGORYID, BARCODE, NAME, DESCRIPTION, PRICE, STOCK, STATUS, CREATEDDATE, VERSION)
VALUES (5,'664322', 'Mascara Flash', '', 5, 5, '1', CURRENT_TIMESTAMP, 0);

INSERT INTO SHSTPRODUCT (CATEGORYID, BARCODE, NAME, DESCRIPTION, PRICE, STOCK, STATUS, CREATEDDATE, VERSION)
VALUES (3,'664323', 'The last adventure Wolverice - Comic', '', 7, 7, '1', CURRENT_TIMESTAMP, 0);

INSERT INTO SHSTPRODUCT (CATEGORYID, BARCODE, NAME, DESCRIPTION, PRICE, STOCK, STATUS, CREATEDDATE, VERSION)
VALUES (4,'664324', 'Mini Aquaman forever', '', 20, 2, '1', CURRENT_TIMESTAMP, 0);